[project]
name = "hw2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.1,<3.12.0"
dependencies = [
    "matplotlib>=3.10.0",
    "numpy>=2.2.1",
    "scikit-learn>=1.6.1",
]
